### ISSUE TITLE
Interdire les attaques de zone sur une case vide

### ISSUE THREAD

**Issue by glecorve** [glecorve/PhantasticasBellum#6]

**Comment by jnokaya** [comment]
Je pense qu'on peut quand même lui autoriser une attaque de zone tant qu'il y a un personnage dans la zone (l'attaque de zone a une zone de 1 autour de la case centrale (9 cases)).
En interdisant les attaques de zone sur une case vide, on supprimerait ainsi l'opportunité de toucher plusieurs personnages qui se situeraient dans une zone dont le centre serait vide.

**Comment by glecorve** [comment]
En supprimant ces opportunités, on réduit assez drastiquement le nombre de coups possibles et donc le facteur de branchement. Je pense que c'est dans l'intérêt de l'intelligence artificielle. De toute manière, la même règle serait appliquée à tout le monde.

**Comment by glecorve** [comment]
Fait.
